### ISSUE TITLE
Refresh token isn't valid on createAnonymousUser mutation

### ISSUE THREAD

**Issue by azimgd** [real-social-media/backend#251]
Can't figure out a way to add refresh token support for anonymous users on frontend client. Trying to implement following sequence:
1. Generate fresh identity on frontend [amplify.currentCredentials](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#currentcredentials)
2. Get tokens from [mutations.createAnonymousUser](https://github.com/real-social-media/backend/blob/develop/real-main/schema.graphql#L83)
3. Federated signin with `IdToken` from step 2
```[`cognito-idp.${Config.AWS_COGNITO_REGION}.amazonaws.com/${Config.AWS_COGNITO_USER_POOL_ID}`]```
4. Advance in time and trigger refreshHandler with `RefreshToken` from step 2 and `endpoint` from step 3

Refresh will token will fail with error below:
```js
{
        code: 'NotAuthorizedException',
        name: 'NotAuthorizedException',
        message: 'Invalid Refresh Token'
}
```

I use cognito-identity-js to handle token refresh:
```js
// Use case 32 on → https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/README.md

const cognitoUser = new AmazonCognitoIdentity.CognitoUser(userData)
cognitoUser.refreshSession(refreshToken)
```

## Debug
My main suspicion is that frontend and backend use different client id's as suggested here: https://stackoverflow.com/questions/43175882/cognito-user-pool-are-refresh-tokens-tied-to-client-id

https://github.com/real-social-media/backend/blob/36c34dd6006680cca56e25bb9aa40e8e73f4e705/real-main/app/models/user/manager.py#L158

https://github.com/real-social-media/backend/blob/36c34dd6006680cca56e25bb9aa40e8e73f4e705/real-main/app/clients/cognito.py#L79-L86

Not sure which client id backend uses but frontend utilizes something like `USER_POOL_WEB_CLIENT_ID`

## Observation
refreshToken.length from mutations.createAnonymousUser is always: 1713
refreshToken.length from amplify is always: 1802

**Comment by azimgd** [comment]
Just to clarify `IdToken` from `mutations.createAnonymousUser` works while `RefreshToken` from same response fails. I sent you reproduction case repo in #backend channel. Could it be that i'm using wrong mechanism to trigger token refresh ? @zkhin @mfogel

**Comment by mfogel** [comment]
I'll take a look into this today @azim. This could definetely be caused by the backend and frontend using different cognito clients, like you suggest.

BTW - the #backend channel on slack - I'm not in that anymore. I'm not sure what its status is. I just added you to #real-social-backend which I think replaces the old #backend channel.

**Comment by Azim** [comment]
oh hey someone pinged me instead of @azimgd for the second time now, please use the "quote reply" function or the @ sign in the message editor to directly mention participants of the issue
<details><summary>how to tag people in the issue</summary>

![image](https://user-images.githubusercontent.com/16478424/123636902-0d64d180-d826-11eb-980a-5757c9485b0d.png)

</details>

**Comment by mfogel** [comment]
Woops, sorry azim! Thank you for the heads up.
